/**
 * DELIVER A RIG - to a browser, not to a video.
 *
 * A rig is a function of time, and the studio has only ever fed it a
 * clock. A page can feed it a SCROLL POSITION and get the same pose out,
 * because it is the same arithmetic - which is the whole return on
 * "motion is sampled from a function of time" rather than baked into
 * frames. A video cannot be scrubbed by a scrollbar; a function can.
 *
 * So this ships three things and no more:
 *
 *   parts/*.webp   the pixels, already cut
 *   rig.json       pivots, parents, rest positions, clips
 *   pose.mjs       THE STUDIO'S OWN MATHS FILE, VERBATIM
 *
 * That third one is the point. Two implementations of a bend chain agree
 * until the day one of them is fixed, and the one that is not fixed is
 * always the one on the site. pose.mjs imports nothing, which is not
 * tidiness - it is what makes shipping it possible at all.
 *
 * What is NOT shipped: any opinion about how the page draws it. The
 * runtime hands back a left, a top, a rotation and an origin per part;
 * whether those become SVG transforms, CSS, or something else is the
 * consuming project's business, and the studio has no view.
 */
import sharp from 'sharp'
import { readFileSync, writeFileSync, copyFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadRig, checkRig } from '../lib/rig.mjs'
import { CANON, STUDIO, ensure, deliverTo } from '../lib/env.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))

export async function deliverRig(name, { to, yes = false, budget = null, quality = 86, log = console.log } = {}) {
  const rig = loadRig(CANON, name)
  const problems = checkRig(rig)
  if (problems.length) throw new Error(`${name} is not deliverable:\n  - ${problems.join('\n  - ')}`)

  const dest = to ? join(STUDIO, to) : join(deliverTo(), 'rigs', name)
  // Parts are cut as PNG because the studio composites them losslessly a
  // hundred times per second of video. A PAGE downloads them once and
  // draws them forever, so it wants WebP: this fox is 393KB of PNG and the
  // site's own hand-cut fox sprite is 46KB. Delivering in the studio's
  // working format rather than the consuming project's is how an asset
  // pipeline quietly becomes a performance problem.
  const parts = rig.parts.map((p) => ({
    id: p.id,
    from: join(rig.dir, p.file),
    file: p.file.replace(/\.png$/i, '.webp'),
    to: join(dest, p.file.replace(/\.png$/i, '.webp')),
  }))
  for (const p of parts) {
    if (!existsSync(p.from)) throw new Error(`Part "${p.id}" is missing its file: ${p.from}`)
  }

  const kb = parts.reduce((t, p) => t + statSync(p.from).size / 1024, 0)
  log(`${name}: ${parts.length} parts, ${kb.toFixed(1)} KB, ${Object.keys(rig.clips || {}).length} clips`)
  log(`destination: ${dest}`)
  if (budget && kb > budget) {
    throw new Error(`Over budget: ${kb.toFixed(1)} KB against ${budget} KB.`)
  }
  if (!yes) {
    log('\nNothing copied. This writes into another project, so it wants --yes.\n')
    return { dest, parts: parts.length, kb }
  }

  ensure(join(dest, 'parts'))
  let out = 0
  for (const p of parts) {
    const buf = await sharp(p.from).webp({ quality, effort: 6 }).toBuffer()
    writeFileSync(p.to, buf)
    out += buf.length / 1024
  }
  log(`  parts re-encoded to WebP: ${kb.toFixed(1)} KB -> ${out.toFixed(1)} KB`)

  // The rig as the browser needs it: no `dir`, which is a studio path and
  // means nothing on a page, and no `source`, which is the whole canon
  // image the parts were cut from and is not shipped.
  const { dir, source, ...browser } = rig
  // The parts were re-encoded, so the manifest has to say so. A rig.json
  // pointing at .png next to a folder of .webp is seven 404s and a page
  // that renders nothing, and it would be found in a browser rather than
  // here.
  const byId = new Map(parts.map((p) => [p.id, p.file]))
  browser.parts = browser.parts.map((p) => ({ ...p, file: byId.get(p.id) ?? p.file }))
  writeFileSync(join(dest, 'rig.json'), JSON.stringify(browser, null, 2) + '\n')

  // Verbatim. Not generated from, not adapted - copied.
  copyFileSync(join(HERE, '..', 'lib', 'pose.mjs'), join(dest, 'pose.mjs'))

  writeFileSync(join(dest, 'README.md'), readme(name, rig))
  log(`Delivered ${parts.length} parts, rig.json, pose.mjs and a README to ${dest}`)
  return { dest, parts: parts.length, kb }
}

function readme(name, rig) {
  const clips = Object.keys(rig.clips || {})
  return `# ${name} - a rig, delivered

Generated by the studio. Do not edit anything here by hand: re-run
\`node run.mjs deliver-rig ${name} --yes\` and it is all replaced.

    parts/       the cut pixels, ${rig.parts.length} of them
    rig.json     pivots, parents, rest positions, clips
    pose.mjs     the studio's own maths, copied verbatim

## Driving it

\`pose.mjs\` imports nothing, so it works in a browser as it is. Two
functions matter:

    import { poseAt, solve, transformOf } from './pose.mjs'
    import rig from './rig.json'

    const pose = poseAt(rig.clips.${clips[0] || 'idle'}, t)
    for (const part of solve(rig, pose)) {
      const { left, top, rotate, origin, z, file } = transformOf(part)
      // place an <img src={file}> at left/top, rotate it about origin
    }

\`t\` is SECONDS, and nothing cares where it comes from. A clock gives the
same loop the studio renders to video. A scroll position gives a scrubbed
version of it - the rig is a function, so it can be evaluated backwards,
paused, or driven at any rate, which is the one thing a video cannot do.

Coordinates are in the rig's own canvas space (${rig.canvas.w}x${rig.canvas.h}),
so scale the whole group rather than the parts: scaling parts individually
moves every joint.

## Clips

${clips.map((c) => `- \`${c}\` - period ${rig.clips[c].period}s`).join('\n') || '- (none declared)'}

A clip's period is the loop length. Every frequency in it divides that
period, which is checked at author time - so evaluating at \`t\` and at
\`t + period\` gives the same pose, exactly.
`
}
